import 'package:flutter/material.dart';
import 'package:sizer/sizer.dart';
import '../utils/responsive.dart';

class Support extends StatelessWidget {
  const Support({super.key});

  @override
  Widget build(BuildContext context) {
    List<String> countries = [
      "Algeria",
      "American Samoa",
      "Angola",
      "Anguilla",
      "Antarctica",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "Australia",
      "Austria",
      "Azerbaijan",
      "The Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "British Indian Ocean Territory",
      "British Virgin Islands",
      "Brunei",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cape Verde",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Caribbean Netherlands",
      "Cayman Islands",
      "Central African Republic",
      "Chad",
      "Chile",
      "Christmas Island",
      "Cocos (Keeling) Islands",
      "Colombia",
      "Comoros",
      "Cook Islands",
      "Ivory Coast",
      "Costa Rica",
      "Croatia",
      "Curaçao",
      "Czech Republic",
      "Democratic Republic of the Congo",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Eswatini",
      "Ethiopia",
      "Falkland Islands",
      "Fiji",
      "Finland",
      "France",
      "Gabon",
      "The Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Gibraltar",
      "Greece",
      "Grenada",
      "Guam",
      "Guatemala",
      "Guernsey",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Heard Island and McDonald Islands",
      "Honduras",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iraq",
      "Ireland",
      "Isle of Man",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jersey",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Kyrgyzstan",
      "Kuwait",
      "Laos",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Micronesia",
      "Mongolia",
      "Montenegro",
      "Montserrat",
      "Morocco",
      "Mozambique",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Niue",
      "Norfolk Island",
      "North Macedonia",
      "Northern Mariana Islands",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestine",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Pitcairn Islands",
      "Poland",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Republic of Cyprus",
      "Republic of the Congo",
      "Romania",
      "Rwanda",
      "Saint Barthélemy",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Pierre and Miquelon",
      "Saint Vincent and the Grenadines",
      "Saint Helena, Ascension and Tristan da Cunha",
      "Samoa",
      "São Tomé and Príncipe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Georgia and the South Sandwich Islands",
      "South Korea",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "Sudan",
      "Suriname",
      "Sweden",
      "Switzerland",
      "Taiwan",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "Timor-Leste",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Turks and Caicos Islands",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Kingdom",
      "United Arab Emirates",
      "United States",
      "United States Minor Outlying Islands",
      "U.S. Virgin Islands",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Venezuela",
      "Vietnam",
      "Wallis and Futuna",
      "Western Sahara",
      "Yemen",
      "Zambia",
      "Zimbabwe"
    ];

    Widget buildCountryText(String country) {
      return Text(
        country,
        style: MediaQuery.of(context).size.width < 340 ||
                MediaQuery.of(context).size.width < 930
            ? TextStyle(
                color: Colors.black,
                fontSize: 13.sp,
              )
            : TextStyle(
                color: Colors.black,
                fontSize: 4.sp,
              ),
      );
    }

    return Scaffold(
        backgroundColor: Colors.white,
        body: ResponsiveWidget(
          mobile: SafeArea(
            child: SingleChildScrollView(
              physics: const ClampingScrollPhysics(),
              child: Column(
                children: [
                  SizedBox(height: 2.h),
                  Padding(
                    padding: EdgeInsets.only(top: 2.h, bottom: 3.h),
                    child: Text(
                      "Yoobble ",
                      style: TextStyle(
                          color: Colors.black,
                          fontSize: 18.sp,
                          fontWeight: FontWeight.bold),
                    ),
                  ),
                  Text(
                    "Countries and territories officially supported at the moment",
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10.sp,
                    ),
                  ),
                  Text(
                    "However no geographic restrictions, let a way to use with VPNs",
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10.sp,
                    ),
                  ),
                  SizedBox(height: 2.h),
                  ListView.builder(
                    shrinkWrap: true,
                    physics: const ClampingScrollPhysics(),
                    itemCount: countries.length,
                    itemBuilder: (context, index) {
                      return Padding(
                        padding: const EdgeInsets.all(10.0),
                        child: buildCountryText(countries[index]),
                      );
                    },
                  ),
                ],
              ),
            ),
          ),
          ////////////////////////////////////////////////////DESKTOP////////////////////////////////////////////////////
          desktop: SingleChildScrollView(
            child: Column(
              children: [
                Padding(
                  padding: EdgeInsets.only(top: 5.h, bottom: 3.h),
                  child: Text(
                    "Yoobble ",
                    style: TextStyle(
                        color: Colors.black,
                        fontSize: 7.sp,
                        fontWeight: FontWeight.bold),
                  ),
                ),
                Text(
                  "Countries and territories officially supported at the moment",
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 4.sp,
                  ),
                ),
                Text(
                  "However no geographic restrictions, let a way to use with VPNs",
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 4.sp,
                  ),
                ),
                Padding(
                  padding: EdgeInsets.only(top: 5.h, bottom: 2.h, left: 7.w),
                  child: GridView.builder(
                    shrinkWrap: true,
                    gridDelegate:
                        const SliverGridDelegateWithFixedCrossAxisCount(
                      childAspectRatio: 7,
                      crossAxisCount: 4,
                    ),
                    itemCount: countries.length,
                    itemBuilder: (context, index) {
                      return Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: buildCountryText(countries[index]),
                      );
                    },
                  ),
                ),
              ],
            ),
          ),
        ));
  }
}
